- name: Configure Node.js web app host on private server
  hosts: private
  become: true
  tasks:

    - name: Update server
      apt: 
        update_cache: true

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Node.js 21.x from NodeSource
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -
        sudo apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Install npm (if not installed)
      apt:
        name: npm
        state: present

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Copy package.json
      copy:
        src: ../deploy-code/package.json
        dest: /home/ubuntu/package.json
        mode: '0644'

    - name: Copy nodejs app from host to private server
      copy: 
        src: ../deploy-code/app.js
        dest: /home/ubuntu/app.js
        mode: '0644'

    - name: Install Node.js dependencies
      npm:
        path: /home/ubuntu
        production: yes

    - name: Start Node.js app with pm2
      shell: pm2 start /home/ubuntu/app.js --name "iac-webapp" && pm2 save
